ALTER TABLE places ADD COLUMN latitude DECIMAL(10,7) NULL;
ALTER TABLE places ADD COLUMN longitude DECIMAL(10,7) NULL;
ALTER TABLE places ADD COLUMN map_url VARCHAR(1200) NULL;
ALTER TABLE places ADD COLUMN google_place_id VARCHAR(255) NULL;
