CREATE TABLE IF NOT EXISTS review_contents (
  id BIGINT NOT NULL AUTO_INCREMENT,
  source_system VARCHAR(64) NOT NULL,
  source_content_item_id BIGINT NOT NULL,
  content_type ENUM('place','event') NOT NULL,
  status ENUM('draft','pending_review','needs_revision','published') NOT NULL DEFAULT 'draft',
  lang VARCHAR(8) NOT NULL DEFAULT 'th',
  category VARCHAR(64) NULL,
  title VARCHAR(255) NOT NULL,
  body LONGTEXT NOT NULL,
  excerpt TEXT NULL,
  meta_title VARCHAR(255) NULL,
  meta_description VARCHAR(320) NULL,
  event_period_text TEXT NULL,
  location_text TEXT NULL,
  latitude DECIMAL(10,7) NULL,
  longitude DECIMAL(10,7) NULL,
  map_url VARCHAR(1200) NULL,
  google_place_id VARCHAR(255) NULL,
  transport_subtype VARCHAR(64) NULL,
  transport_contact_name VARCHAR(255) NULL,
  transport_contact_phone VARCHAR(120) NULL,
  transport_contact_details TEXT NULL,
  transport_link_url VARCHAR(1200) NULL,
  slug VARCHAR(255) NULL,
  slug_locked TINYINT(1) NOT NULL DEFAULT 0,
  public_entity_type ENUM('place','event') NULL,
  public_entity_id BIGINT NULL,
  current_batch_uid CHAR(36) NOT NULL,
  review_payload_json LONGTEXT NULL,
  handoff_snapshot_json LONGTEXT NULL,
  published_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_review_contents_source (source_system, source_content_item_id, content_type),
  KEY idx_review_contents_status (status, updated_at),
  KEY idx_review_contents_public_entity (public_entity_type, public_entity_id)
);
