CREATE TABLE IF NOT EXISTS review_content_assets (
  id BIGINT NOT NULL AUTO_INCREMENT,
  review_content_id BIGINT NOT NULL,
  batch_uid CHAR(36) NOT NULL,
  usage_type ENUM('cover','gallery','inline') NOT NULL,
  position INT NOT NULL DEFAULT 0,
  source_url VARCHAR(1200) NOT NULL,
  resolved_source_url VARCHAR(1200) NULL,
  backend_url VARCHAR(1200) NOT NULL,
  storage_disk ENUM('local') NOT NULL DEFAULT 'local',
  storage_path VARCHAR(1200) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(120) NULL,
  size_bytes BIGINT NULL,
  checksum CHAR(64) NULL,
  status ENUM('review_ready','published','deleted') NOT NULL DEFAULT 'review_ready',
  asset_origin ENUM('collector_import') NOT NULL DEFAULT 'collector_import',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_review_content_assets_batch (review_content_id, batch_uid),
  KEY idx_review_content_assets_status (status),
  KEY idx_review_content_assets_checksum (checksum),
  CONSTRAINT fk_review_content_assets_content FOREIGN KEY (review_content_id) REFERENCES review_contents(id) ON DELETE CASCADE
);
