import { notFound } from "next/navigation";

const PAGE_COPY = {
  en: {
    title: "Public Transport Map",
    subtitle: "Interactive map showing all public transport routes on one page.",
    empty: "No transport routes found in the system.",
    noApiKey: "Google Maps API key is missing.",
    loadFailed: "Failed to load Google Maps.",
    routeNumber: "Route no.",
    vehicleType: "Vehicle",
    distance: "Distance",
    stops: "Stops",
    km: "km",
    routeListTitle: "Route List",
    showAll: "Show all routes",
    focusRoute: "Focus",
    showOnly: "Show only",
    fullscreen: "Full Screen",
    exitFullscreen: "Exit Full Screen",
    typeLabel: { songthaew: "Songthaew", minibus: "Minibus", bus: "Bus", van: "Van" },
  },
  th: {
    title: "Public Transport Map",
    subtitle: "แผนที่แบบโต้ตอบ แสดงทุกเส้นทางไว้ในหน้าเดียว",
    empty: "ยังไม่พบสายรถในระบบ",
    noApiKey: "ไม่พบ Google Maps API key",
    loadFailed: "โหลด Google Maps ไม่สำเร็จ",
    routeNumber: "เลขสาย",
    vehicleType: "ประเภทรถ",
    distance: "ระยะทาง",
    stops: "จุดจอด",
    km: "กม.",
    routeListTitle: "รายการเส้นทาง",
    showAll: "แสดงทุกเส้นทาง",
    focusRoute: "โฟกัส",
    showOnly: "แสดงเฉพาะ",
    fullscreen: "เต็มจอ",
    exitFullscreen: "ออกจากเต็มจอ",
    typeLabel: { songthaew: "รถสองแถว", minibus: "มินิบัส", bus: "รถเมล์", van: "รถตู้" },
  },
  zh: {
    title: "公共交通地图",
    subtitle: "在一个页面中显示所有公共交通线路的交互式地图。",
    empty: "系统中暂无线路数据",
    noApiKey: "缺少 Google Maps API key",
    loadFailed: "Google Maps 加载失败",
    routeNumber: "线路编号",
    vehicleType: "车辆类型",
    distance: "距离",
    stops: "站点",
    km: "公里",
    routeListTitle: "线路列表",
    showAll: "显示全部线路",
    focusRoute: "聚焦",
    showOnly: "仅显示",
    fullscreen: "全屏",
    exitFullscreen: "退出全屏",
    typeLabel: { songthaew: "双条车", minibus: "小巴", bus: "公交车", van: "面包车" },
  },
  lo: {
    title: "ແຜນທີ່ຂົນສົ່ງສາທາລະນະ",
    subtitle: "ແຜນທີ່ແບບ interactive ທີ່ລວມທຸກເສັ້ນທາງໄວ້ໃນຫນ້າດຽວ",
    empty: "ຍັງບໍ່ພົບຂໍ້ມູນເສັ້ນທາງໃນລະບົບ",
    noApiKey: "ບໍ່ພົບ Google Maps API key",
    loadFailed: "ໂຫຼດ Google Maps ບໍ່ສຳເລັດ",
    routeNumber: "ເລກສາຍ",
    vehicleType: "ປະເພດລົດ",
    distance: "ໄລຍະທາງ",
    stops: "ຈຸດຈອດ",
    km: "ກມ.",
    routeListTitle: "ລາຍການເສັ້ນທາງ",
    showAll: "ສະແດງທຸກເສັ້ນທາງ",
    focusRoute: "ໂຟກັສ",
    showOnly: "ສະແດງສະເພາະ",
    fullscreen: "ເຕັມຈໍ",
    exitFullscreen: "ອອກຈາກເຕັມຈໍ",
    typeLabel: { songthaew: "ລົດສອງແຖວ", minibus: "ມິນິບັດ", bus: "ລົດເມ", van: "ລົດຕູ້" },
  },
};

export default function TransportPublicMap() {
  notFound();
}
