import { normalizeLang } from "@/lib/site";

const LOCALE_MAP = {
  en: "en-US",
  th: "th-TH",
  zh: "zh-CN",
  lo: "lo-LA",
};

const DECISION_COPY = {
  th: {
    heroHeading: "ไปเที่ยวอุบล ไปไหนดีวันนี้?",
    heroHint: "เริ่มจากโจทย์ของคุณ แล้วระบบจะพาไปหมวดที่เหมาะทันที",
    searchPlaceholder: "พิมพ์: คาเฟ่ / ที่เที่ยว / งบ 500",
    searchLabel: "เริ่มเลือก",
    quickActions: [
      { label: "เที่ยววันเดียว", href: "attractions" },
      { label: "คาเฟ่วิวสวย", href: "cafes?scenario=scenic-cafe" },
      { label: "ร้านอาหารเด็ด", href: "restaurants?scenario=signature-food" },
    ],
    selectedTitle: "เลือกให้แล้ว",
    selectedSubtitle: "ชุดแนะนำที่กดต่อได้ทันทีเพื่อช่วยตัดสินใจเร็วขึ้น",
    selectedTop10: "เริ่มจากที่เที่ยวเหล่านี้",
    selectedCafe: "เริ่มจากคาเฟ่เหล่านี้",
    selectedEvening: "ตัวเลือกช่วงเย็น",
    selectedCardSummary: "เริ่มจากรายการเด่นก่อน แล้วค่อยแตกไปยังหมวดหรือ scenario ที่ตรงโจทย์มากขึ้น",
    trendingTitle: "อัปเดตล่าสุด",
    trendingSubtitle: "อัปเดตจากอีเวนต์และสถานที่ที่เพิ่งอนุมัติ",
    trendingEvents: "อีเวนต์มาใหม่",
    trendingPlaces: "สถานที่เพิ่งเข้าระบบ",
    scenariosTitle: "ตามสถานการณ์",
    scenariosSubtitle: "เลือกตามเวลา งบประมาณ และคนที่เดินทางด้วย",
    scenarios: [
      { key: "day_trip", title: "เที่ยววันเดียว", description: "แพลนจบในวันเดียว เดินทางไม่ซับซ้อน", href: "attractions" },
      { key: "budget", title: "งบ 500", description: "คุมงบแบบเที่ยวได้ กินได้ และยังสนุก", href: "restaurants?scenario=budget-500" },
      { key: "couple", title: "มากับแฟน", description: "บรรยากาศดี ถ่ายรูปสวย เหมาะกับคู่รัก", href: "cafes?scenario=couple" },
      { key: "family", title: "มากับครอบครัว", description: "เดินง่าย เด็กและผู้ใหญ่ไปด้วยกันได้", href: "attractions?scenario=family" },
    ],
    exploreTitle: "Explore",
    exploreSubtitle: "หมวดทั้งหมดสำหรับคนที่อยากสำรวจเอง",
    insightsTitle: "ก่อนออกไป",
    insightsSubtitle: "ข้อมูลสั้น ๆ ที่ช่วยตัดสินใจก่อนเลือกที่ไปต่อ",
    weatherBlock: "สภาพอากาศวันนี้",
    temperatureBlock: "อุณหภูมิ",
    conditionBlock: "สภาพอากาศ",
    aqiBlock: "คุณภาพอากาศ",
    updatedOn: "อัปเดตเมื่อ",
    openAll: "เปิดทั้งหมด",
    viewMore: "ดูเพิ่มเติม",
    dataPending: "ใช้ข้อมูลจริงจากอากาศ หมวดที่เด่น และความพร้อมของข้อมูลเดินทาง",
    publishedPlaces: "เนื้อหาที่ approved แล้ว",
    transportReady: "ข้อมูลการเดินทางที่พร้อมใช้งาน",
  },
  en: {
    heroHeading: "Where should I go in Ubon today?",
    heroHint: "Start with your intent and jump straight to the right picks.",
    searchPlaceholder: "Type: cafe / attractions / budget 500",
    searchLabel: "Start",
    quickActions: [
      { label: "Day Trip", href: "attractions" },
      { label: "Scenic Cafes", href: "cafes?scenario=scenic-cafe" },
      { label: "Top Food Spots", href: "restaurants?scenario=signature-food" },
    ],
    selectedTitle: "Picked For You",
    selectedSubtitle: "Curated shortcuts to help you decide quickly",
    selectedTop10: "Start With These Places",
    selectedCafe: "Start With These Cafes",
    selectedEvening: "Evening Options",
    selectedCardSummary: "Start with the top picks, then dive into categories or scenarios that match your intent.",
    trendingTitle: "Latest Updates",
    trendingSubtitle: "Freshly approved content and latest events",
    trendingEvents: "New Events",
    trendingPlaces: "Recently Added Places",
    scenariosTitle: "By Situation",
    scenariosSubtitle: "Choose by time, budget, and who you travel with",
    scenarios: [
      { key: "day_trip", title: "One-day Trip", description: "Simple plan you can finish in one day", href: "attractions" },
      { key: "budget", title: "Budget 500", description: "Keep costs tight without losing fun", href: "restaurants?scenario=budget-500" },
      { key: "couple", title: "With Partner", description: "Photo-friendly spots with good atmosphere", href: "cafes?scenario=couple" },
      { key: "family", title: "With Family", description: "Comfortable options for all ages", href: "attractions?scenario=family" },
    ],
    exploreTitle: "Explore",
    exploreSubtitle: "All categories for self-guided browsing",
    insightsTitle: "Before You Go",
    insightsSubtitle: "Quick facts that help you decide before opening the next page",
    weatherBlock: "Today's Weather",
    temperatureBlock: "Temperature",
    conditionBlock: "Conditions",
    aqiBlock: "Air Quality",
    updatedOn: "Updated",
    openAll: "Open All",
    viewMore: "View more",
    dataPending: "Built from live weather, the strongest category, and transport coverage already in the system.",
    publishedPlaces: "Approved places already published",
    transportReady: "Transport entries ready for public utility",
  },
  zh: {
    heroHeading: "今天去乌汶哪里好？",
    heroHint: "先从你的需求开始，系统会带你到更合适的内容。",
    searchPlaceholder: "输入：咖啡馆 / 景点 / 预算 500",
    searchLabel: "开始选择",
    quickActions: [
      { label: "一日游", href: "attractions" },
      { label: "风景咖啡馆", href: "cafes?scenario=scenic-cafe" },
      { label: "精选美食", href: "restaurants?scenario=signature-food" },
    ],
    selectedTitle: "已经帮你选好",
    selectedSubtitle: "先看这些快捷入口，更快做决定",
    selectedTop10: "先从这些地点开始",
    selectedCafe: "先看这些咖啡馆",
    selectedEvening: "傍晚可去",
    selectedCardSummary: "从精选推荐开始，再进入更符合需求的类别或场景。",
    trendingTitle: "最新更新",
    trendingSubtitle: "来自最新通过审核并已发布的内容",
    trendingEvents: "新活动",
    trendingPlaces: "最近加入的地点",
    scenariosTitle: "按情境选择",
    scenariosSubtitle: "按时间、预算和同行对象来选",
    scenarios: [
      { key: "day_trip", title: "一日游", description: "一天内可完成，路线不复杂", href: "attractions" },
      { key: "budget", title: "预算 500", description: "控制花费，也能玩得尽兴", href: "restaurants?scenario=budget-500" },
      { key: "couple", title: "和伴侣同行", description: "氛围好，适合拍照和约会", href: "cafes?scenario=couple" },
      { key: "family", title: "家庭同行", description: "适合各年龄层，走动更轻松", href: "attractions?scenario=family" },
    ],
    exploreTitle: "Explore",
    exploreSubtitle: "想自己逛分类时可从这里进入",
    insightsTitle: "出发前",
    insightsSubtitle: "在继续浏览前，先看几条真正有用的提示",
    weatherBlock: "今日天气",
    temperatureBlock: "气温",
    conditionBlock: "天气",
    aqiBlock: "空气质量",
    updatedOn: "更新于",
    openAll: "查看全部",
    viewMore: "查看更多",
    dataPending: "基于实时天气、当前最强分类，以及系统内已可用的交通信息。",
    publishedPlaces: "已发布并通过审核的地点",
    transportReady: "可公开使用的交通条目",
  },
  lo: {
    heroHeading: "ມື້ນີ້ໄປທ່ຽວອຸບົນທີ່ໃດດີ?",
    heroHint: "ເລີ່ມຈາກສິ່ງທີ່ທ່ານຕ້ອງການ ແລ້ວລະບົບຈະພາໄປຫາຕົວເລືອກທີ່ເໝາະກວ່າ.",
    searchPlaceholder: "ພິມ: ຄາເຟ່ / ສະຖານທີ່ທ່ຽວ / ງົບ 500",
    searchLabel: "ເລີ່ມເລືອກ",
    quickActions: [
      { label: "ທ່ຽວມື້ດຽວ", href: "attractions" },
      { label: "ຄາເຟ່ວິວງາມ", href: "cafes?scenario=scenic-cafe" },
      { label: "ຮ້ານອາຫານເດັ່ນ", href: "restaurants?scenario=signature-food" },
    ],
    selectedTitle: "ເລືອກໄວ້ໃຫ້ແລ້ວ",
    selectedSubtitle: "ທາງລັດທີ່ຊ່ວຍໃຫ້ຕັດສິນໃຈໄດ້ໄວຂຶ້ນ",
    selectedTop10: "ເລີ່ມຈາກສະຖານທີ່ເຫຼົ່ານີ້",
    selectedCafe: "ເລີ່ມຈາກຄາເຟ່ເຫຼົ່ານີ້",
    selectedEvening: "ຕົວເລືອກຕອນແລງ",
    selectedCardSummary: "ເລີ່ມຈາກລາຍການເດັ່ນກ່ອນ ແລ້ວຄ່ອຍເຂົ້າໄປຫາໝວດ ຫຼື scenario ທີ່ຕອບໂຈດຫຼາຍກວ່າ.",
    trendingTitle: "ອັບເດດຫຼ້າສຸດ",
    trendingSubtitle: "ຈາກເນື້ອຫາທີ່ອະນຸມັດແລະເຜີຍແຜ່ແລ້ວລ່າສຸດ",
    trendingEvents: "ອີເວັນໃໝ່",
    trendingPlaces: "ສະຖານທີ່ເພີ່ມໃໝ່",
    scenariosTitle: "ຕາມສະຖານະການ",
    scenariosSubtitle: "ເລືອກຕາມເວລາ ງົບປະມານ ແລະ ຄົນທີ່ໄປນຳ",
    scenarios: [
      { key: "day_trip", title: "ທ່ຽວມື້ດຽວ", description: "ຈົບແຜນໄດ້ໃນມື້ດຽວ ເດີນທາງບໍ່ຊັບຊ້ອນ", href: "attractions" },
      { key: "budget", title: "ງົບ 500", description: "ຄຸມຄ່າໃຊ້ຈ່າຍແຕ່ຍັງທ່ຽວໄດ້ສະບາຍ", href: "restaurants?scenario=budget-500" },
      { key: "couple", title: "ມາກັບແຟນ", description: "ບັນຍາກາດດີ ແລະ ເໝາະກັບການຖ່າຍຮູບ", href: "cafes?scenario=couple" },
      { key: "family", title: "ມາກັບຄອບຄົວ", description: "ຕົວເລືອກທີ່ໄປໄດ້ຫຼາຍຊ່ວງອາຍຸ", href: "attractions?scenario=family" },
    ],
    exploreTitle: "Explore",
    exploreSubtitle: "ໝວດທັງໝົດສຳລັບຄົນທີ່ຢາກສຳຫຼວດເອງ",
    insightsTitle: "ກ່ອນອອກໄປ",
    insightsSubtitle: "ຂໍ້ມູນສັ້ນໆ ທີ່ຊ່ວຍຕັດສິນໃຈກ່ອນເຂົ້າໄປດູລາຍລະອຽດ",
    weatherBlock: "ອາກາດມື້ນີ້",
    temperatureBlock: "ອຸນຫະພູມ",
    conditionBlock: "ສະພາບອາກາດ",
    aqiBlock: "ຄຸນນະພາບອາກາດ",
    updatedOn: "ອັບເດດ",
    openAll: "ເປີດທັງໝົດ",
    viewMore: "ເບິ່ງເພີ່ມ",
    dataPending: "ສ້າງຈາກຂໍ້ມູນອາກາດຈິງ, ໝວດທີ່ເດັ່ນ ແລະ ຄວາມພ້ອມຂອງຂໍ້ມູນການເດີນທາງ.",
    publishedPlaces: "ສະຖານທີ່ທີ່ອະນຸມັດແລະເຜີຍແຜ່ແລ້ວ",
    transportReady: "ຂໍ້ມູນການເດີນທາງທີ່ພ້ອມໃຊ້ສາທາລະນະ",
  },
};

function getDecisionCopy(lang) {
  return DECISION_COPY[normalizeLang(lang)] || DECISION_COPY.en;
}

export { LOCALE_MAP, getDecisionCopy };
