export const SUPPORTED_LANGS = ["en", "th", "zh", "lo"];

export const CATEGORY_KEYS = [
  "attractions",
  "activities",
  "hotels",
  "cafes",
  "restaurants",
  "transport",
];

const content = {
  en: {
    siteTitle: "UBONCITY.COM",
    tagline: "Explore Ubon Ratchathani with trusted local picks",
    intro:
      "Find attractions, activities, hotels, cafes, restaurants, and transport info in one place.",
    explore: "Explore Categories",
    weatherTitle: "Weather in Ubon Ratchathani",
    weatherUnavailable: "Unable to load weather right now.",
    weatherNow: "Now",
    weatherFeel: "Feels like",
    weatherRange: "Today",
    weatherWind: "Wind",
    weatherAir: "Air quality",
    weatherLabel: {
      clear: "Clear sky",
      cloudy: "Cloudy",
      fog: "Fog",
      drizzle: "Drizzle",
      rain: "Rain",
      snow: "Snow",
      storm: "Thunderstorm",
      unknown: "Unknown",
    },
    airQualityLabel: {
      good: "Good",
      moderate: "Moderate",
      sensitive: "Unhealthy for sensitive groups",
      unhealthy: "Unhealthy",
      very_unhealthy: "Very unhealthy",
      hazardous: "Hazardous",
      unknown: "Unknown",
    },
    latestEvents: "Latest Event",
    latestEventsEmpty: "No event updates yet.",
    updatedOn: "Approved",
    viewEvent: "View event",
    backHome: "Back to home",
    eventNotFound: "Event not found",
    empty: "No places found for this category yet.",
    readMore: "Read more",
    nav: {
      attractions: "Attractions",
      activities: "Activities",
      hotels: "Hotels",
      cafes: "Cafes",
      restaurants: "Restaurants",
      transport: "Transport",
    },
  },
  th: {
    siteTitle: "UBONCITY.COM",
    tagline: "เที่ยวอุบลราชธานี ครบ จบ ประทับใจ",
    intro:
      "รวมสถานที่ท่องเที่ยว กิจกรรม โรงแรม คาเฟ่ ร้านอาหาร และข้อมูลการเดินทางไว้ในที่เดียว",
    explore: "สำรวจหมวดหมู่",
    weatherTitle: "พยากรณ์อากาศ จ.อุบลราชธานี",
    weatherUnavailable: "ไม่สามารถโหลดพยากรณ์อากาศได้ในขณะนี้",
    weatherNow: "ตอนนี้",
    weatherFeel: "รู้สึกเหมือน",
    weatherRange: "ช่วงอุณหภูมิวันนี้",
    weatherWind: "ลม",
    weatherAir: "คุณภาพอากาศ",
    weatherLabel: {
      clear: "ท้องฟ้าแจ่มใส",
      cloudy: "มีเมฆมาก",
      fog: "มีหมอก",
      drizzle: "ฝนปรอย",
      rain: "ฝนตก",
      snow: "หิมะ",
      storm: "พายุฝนฟ้าคะนอง",
      unknown: "ไม่ทราบสภาพอากาศ",
    },
    airQualityLabel: {
      good: "ดี",
      moderate: "ปานกลาง",
      sensitive: "เริ่มมีผลกระทบต่อกลุ่มเสี่ยง",
      unhealthy: "ไม่ดีต่อสุขภาพ",
      very_unhealthy: "แย่มาก",
      hazardous: "อันตราย",
      unknown: "ไม่ทราบค่า",
    },
    latestEvents: "Latest Event",
    latestEventsEmpty: "ยังไม่มีการอัปเดต Event",
    updatedOn: "อนุมัติเมื่อ",
    viewEvent: "ดูรายละเอียด Event",
    backHome: "กลับหน้าโฮม",
    eventNotFound: "ไม่พบ Event",
    empty: "ยังไม่พบเนื้อหาในหมวดนี้",
    readMore: "อ่านต่อ",
    nav: {
      attractions: "สถานที่ท่องเที่ยว",
      activities: "กิจกรรม",
      hotels: "โรงแรม",
      cafes: "คาเฟ่",
      restaurants: "ร้านอาหาร",
      transport: "การเดินทาง",
    },
  },
  zh: {
    siteTitle: "UBONCITY.COM",
    tagline: "探索乌汶府精选的本地旅行信息",
    intro: "在一个地方找到景点、活动、酒店、咖啡馆、餐厅和交通信息。",
    explore: "浏览分类",
    weatherTitle: "乌汶府天气",
    weatherUnavailable: "暂时无法加载天气数据。",
    weatherNow: "当前",
    weatherFeel: "体感",
    weatherRange: "今日范围",
    weatherWind: "风速",
    weatherAir: "空气质量",
    weatherLabel: {
      clear: "晴朗",
      cloudy: "多云",
      fog: "有雾",
      drizzle: "毛毛雨",
      rain: "下雨",
      snow: "下雪",
      storm: "雷暴",
      unknown: "未知",
    },
    airQualityLabel: {
      good: "优",
      moderate: "良",
      sensitive: "敏感人群不健康",
      unhealthy: "不健康",
      very_unhealthy: "很不健康",
      hazardous: "危险",
      unknown: "未知",
    },
    latestEvents: "最新活动",
    latestEventsEmpty: "暂无活动更新",
    updatedOn: "批准于",
    viewEvent: "查看活动",
    backHome: "返回首页",
    eventNotFound: "未找到活动",
    empty: "该分类暂无内容",
    readMore: "阅读更多",
    nav: {
      attractions: "景点",
      activities: "活动",
      hotels: "酒店",
      cafes: "咖啡馆",
      restaurants: "餐厅",
      transport: "交通",
    },
  },
  lo: {
    siteTitle: "UBONCITY.COM",
    tagline: "ສຳຫຼວດເນື້ອຫາທ່ອງທ່ຽວເມືອງອຸບົນທີ່ເຊື່ອຖືໄດ້",
    intro:
      "ຮວບຮວມສະຖານທີ່ທ່ອງທ່ຽວ ກິດຈະກຳ ໂຮງແຮມ ຄາເຟ ຮ້ານອາຫານ ແລະຂໍ້ມູນການເດີນທາງໃນບ່ອນດຽວ",
    explore: "ສຳຫຼວດໝວດໝູ່",
    weatherTitle: "ພະຍາກອນອາກາດ ອຸບົນຣາດຊະທານີ",
    weatherUnavailable: "ບໍ່ສາມາດໂຫຼດຂໍ້ມູນອາກາດໄດ້ໃນຕອນນີ້",
    weatherNow: "ຕອນນີ້",
    weatherFeel: "ຮູ້ສຶກຄື",
    weatherRange: "ຊ່ວງອຸນຫະພູມມື້ນີ້",
    weatherWind: "ລົມ",
    weatherAir: "ຄຸນນະພາບອາກາດ",
    weatherLabel: {
      clear: "ຟ້າແຈ້ງ",
      cloudy: "ມີເມກ",
      fog: "ມີໝອກ",
      drizzle: "ຝົນປອຍ",
      rain: "ຝົນຕົກ",
      snow: "ຫິມະ",
      storm: "ພາຍຸຟ້າຄະນອງ",
      unknown: "ບໍ່ຮູ້ສະພາບອາກາດ",
    },
    airQualityLabel: {
      good: "ດີ",
      moderate: "ປານກາງ",
      sensitive: "ກະທົບກຸ່ມສ່ຽງ",
      unhealthy: "ບໍ່ດີຕໍ່ສຸຂະພາບ",
      very_unhealthy: "ແຍ່ຫຼາຍ",
      hazardous: "ອັນຕະລາຍ",
      unknown: "ບໍ່ຮູ້ຄ່າ",
    },
    latestEvents: "ອີເວັນລ່າສຸດ",
    latestEventsEmpty: "ຍັງບໍ່ມີການອັບເດດອີເວັນ",
    updatedOn: "ອະນຸມັດເມື່ອ",
    viewEvent: "ເບິ່ງອີເວັນ",
    backHome: "ກັບໜ້າຫຼັກ",
    eventNotFound: "ບໍ່ພົບອີເວັນ",
    empty: "ຍັງບໍ່ພົບເນື້ອຫາໃນໝວດນີ້",
    readMore: "ອ່ານຕໍ່",
    nav: {
      attractions: "ສະຖານທີ່ທ່ອງທ່ຽວ",
      activities: "ກິດຈະກຳ",
      hotels: "ໂຮງແຮມ",
      cafes: "ຄາເຟ",
      restaurants: "ຮ້ານອາຫານ",
      transport: "ການເດີນທາງ",
    },
  },
};

export function normalizeLang(lang) {
  return SUPPORTED_LANGS.includes(lang) ? lang : "en";
}

export function getLangContent(lang) {
  return content[normalizeLang(lang)];
}
